---
title:  "Review Data Wrangling"
type:   assignment
---

# Overview

In this assignment we'll review all of the data wrangling techniques that we've learned over the few weeks.  I've tried to design tasks that mirror the same key steps in data wrangling from my code examples in-class.  I don't want to make this set of tasks artificially difficult, but I'd strongly encourage you to not try to simply copy-and-paste your in-class solutions here.   Think through these problems from first principles.  Getting stuck is a great thing; it'll help us identify areas where you didn't follow what we did in class!

# Data

If you've started this assignment as instructed above, you'll have fresh copies of two source data files in your `data/` subfolder:

* `northern-mean-clean.csv`
* `southern-mean-clean.csv`

Click on these files using the "Files" tab in RStudio to see what they look like.

Load both using `read.csv`, and call these variables `north` and `south`, respectively. Check that `head` shows the following for each, respectively:

```{r solution}
north <- read.csv("data/northern-mean-clean.csv")
south <- read.csv("data/southern-mean-clean.csv")

head(north)
head(south)
```



